### ISSUE TITLE
macbook air 7,2

### ISSUE THREAD

**Issue by nobitches** [gch1p/mmga#2]
hi, would you think that it would be possible to coreboot a macbook air 7,2 (2017)
Sorry if i opened an issue but i'm a bit noob with github.

**Comment by gch1p** [comment]
Hi. Currently, it's not supported. I have this model too, and I remember checking whether it has Intel Boot Guard enabled, and, if I recall correctly, it has not. So, in theory, yes, it's possible to port coreboot on it. But someone would have to do it. Maybe I, but right now I'm too busy with other business. Maybe next year, definitely not in the next few months.

**Comment by nobitches** [comment]
hi, thanks for the reply. I could actually try to port coreboot to the macbook air 7,2. maybe when i have some free time i'll put my hands on my macbook. Have a nice day.
I'll let you know if i come up with something.

**Comment by gch1p** [comment]
Closing for now. Feel free to re-open when you'll have some news.
