### ISSUE TITLE
Supported models

### ISSUE THREAD

**Issue by startergo** [gch1p/mmga#4]
Curious how did you find out MacBook Pro 10,1 is supported? it is nowhere in the supported motherboards list.

**Comment by gch1p** [comment]
Because I ported it. It will be, one day. https://review.coreboot.org/c/coreboot/+/32673

**Comment by startergo** [comment]
Interesting. I assume it should work with all 10.1 models right? I am thinking of buying one for testing. Can you boot OSX with core boot?

**Comment by gch1p** [comment]
About OS X: I never tried, I'm sure it will not work with coreboot out of box, but it might work with tianocore+clover or tianocore+opencore, but it will be a hackintosh after that, not "real" mac.

**Comment by gch1p** [comment]
2012 models will work because I have one of them (the one with I7-3720QM). Not 100% sure about 2013 models. If the motherboard inside them is the same 820-3332-A board then they should work too, but I'm not sure, because EMC number differs (EMC 2512 vs EMC 2673)...

**Comment by startergo** [comment]
Do you think coreboot  could be ported to MacPro5,1? Did you create any procedure?

**Comment by gch1p** [comment]
> Do you think coreboot could be ported to MacPro5,1?

Yes, if there are schematics available. For example, there are no schematics for MacMinis in public.

Sometimes a board can be ported without schematics, but it depends.

> Did you create any procedure?

I'm not sure what you mean. You asking about how to port a board?

**Comment by startergo** [comment]
> Yes, if there are schematics available.

Interesting. That would be a nice project to test. I can do testing without being afraid of a brick as I plug in to the Little Frank connector with a MATT card.

**Comment by startergo** [comment]
> 2012 models will work because I have one of them (the one with I7-3720QM). Not 100% sure about 2013 models. If the motherboard inside them is the same 820-3332-A board then they should work too, but I'm not sure about that since EMC number differs (EMC 2512 vs EMC 2673)...

![image](https://user-images.githubusercontent.com/7897244/104148476-6b991780-53a0-11eb-8e12-bb76be61200b.png)

They must be the same then
http://www.cmizapper.com/buy/mattcard-macbook-pro.html
